[DOCS-7211] Collaboration Connector for Microsoft 365 2.0
Alfresco/docs-alfresco pull request #1003
Opened 2023-05-09 20:34 UTC by Amy-Hyland

2023-05-11 07:36 UTC, dsibilio submitted a review, later dismissed

2023-05-11 11:13 UTC, mpichura submitted a review, later dismissed
LGTM

2023-05-11 16:55 UTC, anxumalo requested changes
Looks good - just a few minor fixes please

2023-05-11 16:55 UTC, anxumalo commented on microsoft-365/1.1/support/index.md
> +| Alfresco Content Services 7.0.0 | |
According to the [Alfresco Product Support Status page](https://www.alfresco.com/services/subscription/technical-support/product-support-status), MS 365 1.1 is also compatible with ACS 7.3: 

```suggestion
| Alfresco Content Services 7.3.x | |
| Alfresco Content Services 7.2.x | |
| Alfresco Content Services 7.1.x | |
| Alfresco Content Services 7.0.x | |
```

2023-05-11 16:55 UTC, anxumalo commented on microsoft-365/latest/support/index.md
> +| Alfresco Content Services 7.0.0 | |
Let's make these versions more generic to match the lines above:
```suggestion
| Alfresco Content Services 7.2.x | |
| Alfresco Content Services 7.1.x | |
| Alfresco Content Services 7.0.x | |
```

2023-05-12 09:23 UTC, anxumalo approved these changes

2023-05-15 19:23 UTC, merged