[DOCS-7164] Transform Service 2.1
Alfresco/docs-alfresco pull request #1017
Opened 2023-05-18 21:08 UTC by Amy-Hyland

2023-05-24 09:36 UTC, anxumalo requested changes
@Amy-Hyland  Sending early feedback for your consideration

2023-05-30 20:30 UTC, Amy-Hyland commented on transform-service/latest/support/index.md
done

2023-05-30 20:31 UTC, Amy-Hyland commented on transform-service/latest/install/index.md
> +    > deploy. For example, if you want Content Services 7.3.0, then select tag `7.3.0`.
I changed the 5.3.0 example back.

2023-05-30 20:31 UTC, Amy-Hyland commented on transform-service/latest/install/index.md
They should be included now.

2023-05-31 07:56 UTC, HeinRagas approved these changes
LGTM

2023-05-31 10:16 UTC, anxumalo commented on transform-service/latest/install/index.md
> +    > deploy. For example, if you want Content Services 7.3.0, then select tag `5.3.0`.
Let's change the example to ACS **7.4.0** - tag `6.0.0`

2023-05-31 10:30 UTC, anxumalo commented on transform-service/latest/install/index.md
> +    > deploy. For example, if you want Content Services 7.3.0, then select tag `5.3.0`.
Updated in commit [782fa07](https://github.com/Alfresco/docs-alfresco/pull/1017/commits/782fa07d8413e0d9cbcd31bb19c6d5ee8df111bf)

2023-06-01 15:24 UTC, merged