[DOCS-7231] Add new optional SSO implementation for ACA 3.5.1
Alfresco/docs-alfresco pull request #1040
Opened 2023-06-12 14:25 UTC by anxumalo

2023-06-13 14:17 UTC, dgrumieaux requested changes
this looks great - i did catch one mistake that i made when i supplied the original instructions.

please change:
1. Navigate to the deployed "ocms" web application and edit the file located at `ocms/WEB-INF/assets/config-overrides.js`.

to read:
1. Navigate to the deployed "ocms" web application and edit the file located at `ocms/assets/config-overrides.js`.

2023-06-13 16:57 UTC, katiebrill approved these changes

2023-06-14 09:08 UTC, anxumalo commented
@dgrumieaux File location corrected - please re-review

2023-06-14 16:43 UTC, dgrumieaux approved these changes

2023-06-15 09:36 UTC, merged