[DOCS-7310] Update example release tag for Content Services 7.4
Alfresco/docs-alfresco pull request #1081
Opened 2023-07-07 15:49 UTC by anxumalo

The release tag is only mentioned in the Alfresco Transform Service docs.

2023-07-07 16:06 UTC, gionn requested changes

2023-07-07 16:06 UTC, gionn commented on transform-service/latest/install/index.md
> +    > deploy. For example, if you want Content Services 7.4.0, then select tag `6.0.2`.
```suggestion
    > deploy. For example, if you want Content Services 7.4.0, then select tag `v6.0.2`.
```

tags has always a leading `v`

<img width="691" alt="Screenshot 2023-07-07 at 18 06 06" src="https://github.com/Alfresco/docs-alfresco/assets/71768/733861e9-95e1-49da-a558-64692197f3a1">

2023-07-11 10:02 UTC, gionn approved these changes

2023-07-11 12:04 UTC, oliveralfresco2018 approved these changes
LGTM

2023-07-11 12:06 UTC, merged