[DOCS-7358] Add HR Employee File Management solution to Alfresco Content Accelerator docs
Alfresco/docs-alfresco pull request #1141
Opened 2023-09-20 18:56 UTC by anxumalo

2023-09-21 15:02 UTC, anxumalo commented on content-accelerator/latest/install/install-guide.md
> +   You'll find this WAR file in the `Web Applications` folder of the `alfresco-content-accelerator-policy-and-procedure-accelerator` zip or `alfresco-content-accelerator-sehr-accelerator` zip.
Need to revert this section & move it to step 3 in `install-guide/#install-webapps` section .. _to both subsections_? 🤔

2023-09-21 16:39 UTC, anxumalo commented on content-accelerator/latest/install/install-guide.md
> +   You'll find this WAR file in the `Web Applications` folder of the `alfresco-content-accelerator-policy-and-procedure-accelerator` zip or `alfresco-content-accelerator-sehr-accelerator` zip.
Step 3 moved by commit [f081bee](https://github.com/Alfresco/docs-alfresco/pull/1141/commits/f081bee19ecff9b89e69d7f1142c7e199a221588)

2023-09-22 13:41 UTC, anxumalo commented on content-accelerator/latest/install/install-guide.md
> +   You'll find this WAR file in the `Web Applications` folder of the `alfresco-content-accelerator-policy-and-procedure-accelerator` zip or `alfresco-content-accelerator-sehr-accelerator` zip.
Both Tomcat subsection updated - see latest commit [651cb0b](https://github.com/Alfresco/docs-alfresco/pull/1141/commits/651cb0b620807d13b39bf8090b9420b96dd5ce35)

2023-09-22 15:03 UTC, anxumalo commented on content-accelerator/latest/install/install-guide.md
> +   * If using Alfresco Content Services 7.4.x, use the `tsgrp-opencontent-3.5-for-acs7.4.amp`.
Verify artefact versions

2023-09-22 15:04 UTC, anxumalo commented on _data/toc/content-accelerator.yaml
> +        path: 'content-accelerator/latest/configure/hr-management/'
Fix URL

2023-10-11 16:33 UTC, anxumalo commented on content-accelerator/latest/install/install-guide.md
> +   * If using Alfresco Content Services 7.4.x, use the `tsgrp-opencontent-3.5-for-acs7.4.amp`.
Switched to generic version: `-3.5.x-`

2023-10-11 17:30 UTC, katiebrill submitted a review, later dismissed

2023-10-12 04:12 UTC, mitvachhani approved these changes

2023-10-12 08:52 UTC, oliveralfresco2018 requested changes
one minor change

2023-10-12 08:52 UTC, oliveralfresco2018 commented on content-accelerator/latest/configure/hr-management.md
> +    2. Click **Define Roles** in the **Tools** section, and then click on `New Role` button to the left of page.
```suggestion
    2. Click **Define Roles** in the **Tools** section, and then click on the `New Role` button to the left of page.
```

2023-10-12 09:25 UTC, oliveralfresco2018 approved these changes
LGTM

2023-10-13 11:02 UTC, merged