[DOCS-7143] Bulk metadata indexing
Alfresco/docs-alfresco pull request #1166
Opened 2023-10-11 08:13 UTC by oliveralfresco2018

2023-12-06 10:26 UTC, rainaashis approved these changes
Looks good to me, thanks for the changes

2023-12-15 12:04 UTC, Prosune requested changes

2023-12-15 12:04 UTC, Prosune commented on search-enterprise/3.2/admin/index.md
LGTM. Just a suggestion.
In step 6 of the "setup the Re-Indexing Instance" procedure, I feel the changes I made in italics might be helpful.

* `server.port` - _provide_ a unique port number _as a value of this parameter_ to run the required number of threads needed for an instance. For example, to run 7 threads from instance one, you must copy the code 7 times and provide a unique port in each of the 7 sets of commands.
    * `alfresco.reindex.fromId` and `alfresco.reindex.toId` - _provide_ a unique `nodeID` for each thread. You can equally distribute the total file count among the threads. In this example, 1B among 20 threads with each thread receiving 50 million each.

2023-12-21 04:53 UTC, oliveralfresco2018 commented on search-enterprise/3.2/admin/index.md
I'm happy to leave it as is. Cheers.

2023-12-27 06:37 UTC, merged