[DOCS-7390] Search Enterprise 4.0
Alfresco/docs-alfresco pull request #1170
Opened 2023-10-18 05:11 UTC by oliveralfresco2018

2023-11-06 14:58 UTC, anxumalo requested changes
Since SE 4.0 is only compatible with Alfresco Content Services 23.1, there are several places that still refer to ACS 7.4 (affects top-level `index.md`, `/install`, and `/support` pages).

2023-11-06 14:58 UTC, anxumalo commented on search-enterprise/latest/support/index.md
Replace this line: `| JDK 11 or OpenJDK 11 | |`

with the following block:
```
| | |
| | Check the [Alfresco Content Services Supported platforms]({% link content-services/latest/support/index.md %}) page for specific versions of the individual components. |
| **Java** | |
| JDK x or OpenJDK x | |
| | |`

2023-11-06 17:41 UTC, oliveralfresco2018 commented on search-enterprise/latest/support/index.md
done

2023-11-06 18:12 UTC, anxumalo reviewed
See inline comments - require technical approval

2023-11-07 13:32 UTC, oliveralfresco2018 commented on search-enterprise/latest/support/index.md
> +| JDK x or OpenJDK x | |
done

2023-11-07 16:24 UTC, anxumalo approved these changes
LGTM 👍🏼

2023-11-07 16:25 UTC, merged