[DOCS-7396] Governance Services 23.1
Alfresco/docs-alfresco pull request #1172
Opened 2023-10-19 02:27 UTC by oliveralfresco2018

2023-11-02 14:32 UTC, anxumalo requested changes
Looking good - see inline comments

2023-11-03 11:51 UTC, oliveralfresco2018 commented on governance-services/7.4/upgrade/index.md
> +2. Download Alfresco Content Services 7.4 or above and the Governance Services Distribution ZIP from [Hyland Community](https://community.hyland.com/){:target="_blank"}.
Removed.

2023-11-03 11:52 UTC, oliveralfresco2018 commented on governance-services/latest/upgrade/index.md
> +2. Download Alfresco Content Services 23.1 or above and the Governance Services Distribution ZIP from [Hyland Community](https://community.hyland.com/){:target="_blank"}.
removed.

2023-11-03 18:29 UTC, anxumalo approved these changes
LGTM

2023-11-06 11:26 UTC, merged