[DOCS-7432] Add Healthcheck configuration
Alfresco/docs-alfresco pull request #1177
Opened 2023-10-27 15:42 UTC by oliveralfresco2018

2023-10-30 15:12 UTC, damianujma approved these changes

2023-10-31 09:35 UTC, mjstanford approved these changes

2023-10-31 13:20 UTC, anxumalo requested changes
Cool feature - nice read! Are we writing "healthcheck" as one word or two separate words? The majority of times you've written it as one word. Let's keep it consistent

2023-10-31 13:20 UTC, anxumalo commented on search-enterprise/latest/admin/index.md
> +2. Open the Java Monitoring & management Console window by entering: `jconsole`.
I'm not sure what the correct capitalization is, but can we use initial capitals?
```suggestion
2. Open the Java Monitoring & Management Console window by entering: `jconsole`.
```

2023-10-31 13:20 UTC, anxumalo commented on search-enterprise/latest/admin/index.md
> +The Service Status tab gives information on the status of the latest Healthcheck execution, latest health check settings, and scheduled health check settings. At the bottom of the page there is a lis
```suggestion
The **Service Status** tab gives information on the status of the latest Healthcheck execution, latest health check settings, and scheduled health check settings. At the bottom of the page there is a list of the latest Healthcheck events sorted by date. You can see ranges of nodes where discrepancies in the indexing were found. This means the range starts immediately after the previous correctly indexed node and finishes immediately before the first next correctly indexed node. You can also see the number of issues found within each range.
```

2023-11-01 10:46 UTC, oliveralfresco2018 commented
> Cool feature - nice read! Are we writing "healthcheck" as one word or two separate words? The majority of times you've written it as one word. Let's keep it consistent

No worries, done.

2023-11-01 13:18 UTC, merged