[DOCS-7341] Identify products not supported with the latest ACS version
Alfresco/docs-alfresco pull request #1258
Opened 2023-12-15 16:49 UTC by anxumalo

2023-12-15 17:52 UTC, mjstanford requested changes

2023-12-15 17:52 UTC, mjstanford commented on microsoft-outlook/latest/index.md
> +> **Note:** Alfresco Outlook Integration 2.9 can be applied to Alfresco Content Services 7.0 - 7.3 only.
Only partially compatible for ACS 7.3

2023-12-15 19:03 UTC, anxumalo commented on microsoft-outlook/latest/index.md
> +> **Note:** Alfresco Outlook Integration 2.9 can be applied to Alfresco Content Services 7.0 - 7.3 only.
Ah yes, thanks - relates to #1191.

2023-12-18 16:38 UTC, mjstanford approved these changes

2023-12-19 16:24 UTC, merged