DOCS-7440-Alfresco-Enterprise-Viewer-4.0-docs
Alfresco/docs-alfresco pull request #1303
Opened 2024-01-31 07:38 UTC by mbujak-hyland

2024-02-01 14:54 UTC, anxumalo reviewed
@mbujak-hyland Sending early feedback: 

1. All the links in the `enterprise-viewer/3.6/` folder should have links that point to `enterprise-viewer/3.6/` instead of `latest`.
2. Move the Supported platforms changes in `enterprise-viewer/latest/support/ to this PR, so they're included in the correct file when we publish.

2024-02-02 07:39 UTC, mbujak-hyland commented on enterprise-viewer/latest/install/index.md
> +Starting from Enterprise Viewer 4.0, an enhancement has been added so the socket server URL is fetched from the `appConfig.json` at runtime. This provides users with the capability to change the sock
Fixed all the links in AEV 3.6 from "latest" to "3.6"
Fixed an enhancement information, back to "3.6"
Thank you.

2024-02-28 12:44 UTC, ariadnags approved these changes
LGTM

2024-02-28 12:44 UTC, ariadnags approved these changes

2024-02-28 12:45 UTC, ariadnags approved these changes

2024-02-28 12:45 UTC, ariadnags approved these changes

2024-03-01 16:30 UTC, anxumalo commented on content-services/latest/support/index.md
@mbujak-hyland Please see the unresolved comments in https://github.com/Alfresco/docs-alfresco/pull/1302/files as they affect multiple files for AEV. This ACS change needs to be added to the ACS support branch so that we show both the ACS 23.2 and 23.1 compatibility.

2024-03-04 18:12 UTC, anxumalo requested changes
@mbujak-hyland This looks great! 👍🏼 There's 1 inline comment we need to address before merging.

2024-03-04 18:12 UTC, anxumalo commented on enterprise-viewer/latest/install/index.md
> +   where `x` is the specific Content Services version you're running.
I've added a generic example here for 23.x. Need to verify if this is the correct file format in the release artefacts.

2024-03-05 15:54 UTC, anxumalo approved these changes
LGTM 👍🏼

2024-03-05 20:02 UTC, merged