[DOCS-7518] Add note about security levels in Salesforce Connector app
Alfresco/docs-alfresco pull request #1311
Opened 2024-01-31 17:44 UTC by anxumalo

2024-01-31 18:12 UTC, jottley approved these changes

2024-02-01 06:56 UTC, ariadnags commented on salesforce/latest/install/index.md
"Selecting a security level can have an affect on future usage."
I think it's supposed to be an effect?

2024-02-01 06:56 UTC, ariadnags requested changes
"Selecting a security level can have an affect on future usage."
I think it's supposed to be an effect?

2024-02-01 07:10 UTC, anxumalo commented
> "Selecting a security level can have an affect on future usage." I think it's supposed to be an effect?

@ariadnags Good point ..  we have a choice of using either "_can affect.._."  or "_have an effect on .._". I'll use the latter.

2024-02-01 07:33 UTC, ariadnags approved these changes
LGTM

2024-02-01 07:40 UTC, merged