[DOCS-7624] Update Supported Platforms in Search modules
Alfresco/docs-alfresco pull request #1396
Opened 2024-03-13 11:11 UTC by Prosune

2024-03-13 16:39 UTC, anxumalo requested changes
Please see inline comments - I also expected to see changes in the ACS Supported platforms pages

2024-03-14 07:29 UTC, Prosune commented on insight-engine/latest/support/index.md
These versions appear to be included. I could not see them initially but when I expanded, I could see them.

2024-03-14 07:29 UTC, Prosune commented on search-enterprise/latest/support/index.md
> -| | |
These versions appear to be included. I could not see them initially but when I expanded, I could see them.

2024-03-14 07:30 UTC, Prosune commented on search-services/latest/support/index.md
These versions appear to be included. I could not see them initially but when I expanded, I could see them.

2024-03-14 07:33 UTC, Prosune commented on search-enterprise/latest/support/index.md
> -| | |
Done

2024-03-14 18:16 UTC, anxumalo approved these changes

2024-03-15 11:50 UTC, merged