[DOCS-7617] Update AGS Community files
Alfresco/docs-alfresco pull request #1421
Opened 2024-04-01 09:29 UTC by aritrihore

2024-04-04 14:24 UTC, anxumalo requested changes
I discovered a few minor fixes after checking the released artefacts (see JIRA ticket for additional comments).

2024-04-04 14:24 UTC, anxumalo commented on governance-services/community/install/zip.md
In this page, let’s change all the **AMP** file versions to be more generic: `23.2.x.xxx`

2024-04-04 14:24 UTC, anxumalo commented on governance-services/community/develop/index.md
> +The Governance Services distribution zip contains the `alfresco-governance-services-community-rest-api-explorer-23.2.1.xxx.war` file.
Let’s change the **WAR** file version to be more generic: `23.2.x.xxx`

```suggestion
The Governance Services distribution zip contains the `alfresco-governance-services-community-rest-api-explorer-23.2.x.xxx.war` file.
```

2024-04-04 14:24 UTC, anxumalo commented on governance-services/community/install/zip.md
> +    java -jar bin\alfresco-mmt.jar install amps_share\alfresco-governance-services-community-share-23.2.1.xxx.amp tomcat\webapps\share.war
Add a hint about how customers should specify the exact released versions - the additional sentence should be at the same indent level as the `bash` commands:

```suggestion
    java -jar bin\alfresco-mmt.jar install amps_share\alfresco-governance-services-community-share-23.2.x.xxx.amp tomcat\webapps\share.war
```

    Replace `x.xxx` with the exact versions provided in the Governance Services Community Edition distribution zip.

2024-04-05 07:41 UTC, aritrihore commented
> I discovered a few minor fixes after checking the released artefacts (see JIRA ticket for additional comments).

2024-04-05 09:30 UTC, anxumalo approved these changes
LGTM 👍🏼

2024-04-05 09:31 UTC, merged