[DOCS-7460] Remove incorrect properties from solcore.properties
Alfresco/docs-alfresco pull request #1471
Opened 2024-05-06 13:22 UTC by Prosune

2024-05-07 12:10 UTC, MattioliLeo approved these changes
LGTM

2024-05-07 20:02 UTC, anxumalo requested changes

2024-05-08 00:51 UTC, asirikaCosta reviewed
I guess we can leave below wordings

Replace `alfresco.secureComms=https` with:
        alfresco.secureComms=secret

Replace the rests with 

Pass alfresco.secureComms.secret as a system property (using -D when starting Solr) by adding the startup parameters in step **7**:

2024-05-23 13:04 UTC, anxumalo approved these changes

2024-05-23 13:10 UTC, merged