[DOCS-7727] Add Keycloak configuration to ACS 7.2
Alfresco/docs-alfresco pull request #1506
Opened 2024-06-05 10:45 UTC by mbujak-hyland

2024-06-05 10:58 UTC, mbujak-hyland commented
Hi @dsibilio,
Since ACS 7.2 is compatible only with Keycloak 24.0.3, if I update Keycloak configuration with the following GitHub reference: https://github.com/Alfresco/alfresco-identity-service/tree/keycloak-24.0.3_theme-0.3.5, will it be accurate?

I have already updated external links to point to the Keycloak docs of the compatible version: https://www.keycloak.org/docs/24.0.3/server_admin/index.html

Would you approve those changes?
Thank you!

FYI: @anxumalo

2024-06-07 09:40 UTC, dsibilio requested changes

2024-06-07 09:40 UTC, dsibilio commented on content-services/7.2/config/keycloak.md
> +* An overview of Keycloak architecture is provided in the [Alfresco/alfresco-identity-service](https://github.com/Alfresco/alfresco-identity-service/tree/keycloak-21.1.2_theme-0.3.5){:target="_blank"
```suggestion
* An overview of Keycloak architecture is provided in the [Alfresco/alfresco-identity-service](https://github.com/Alfresco/alfresco-identity-service/tree/keycloak-24.0.3_theme-0.3.5){:target="_blank"} GitHub project documentation.
```

2024-06-07 14:36 UTC, dsibilio approved these changes

2024-06-07 14:57 UTC, merged