[DOCS-7766] Add OpenContent properties to Enterprise Viewer 4.0.x
Alfresco/docs-alfresco pull request #1531
Opened 2024-08-12 09:17 UTC by mbujak-hyland

2024-08-20 17:09 UTC, adecatur72 approved these changes
Looks good!

2024-08-21 11:59 UTC, anxumalo requested changes
I've added some minor suggestions and there may be a few properties missing (unless they're included in another PR)

2024-08-21 11:59 UTC, anxumalo commented on enterprise-viewer/latest/config/files.md
> +Default value: `true`
Should this be `false` based on the statement above?  "This defaults to `false`

2024-08-21 11:59 UTC, anxumalo commented on enterprise-viewer/latest/config/files.md
> +The resolution used after coverting the redacted document pages into image format (to remove the text).
```suggestion
The resolution used after converting the redacted document pages into image format (to remove the text).
```

2024-08-21 11:59 UTC, anxumalo commented on enterprise-viewer/latest/config/files.md
> +
I think there are four missing properties with format `ctrlprint.*` - starting from `ctrlprint.lines.per.index.page`.

2024-08-21 11:59 UTC, anxumalo commented on enterprise-viewer/latest/config/files.md
> +The following are paths to the FFMpeg and FFProbe executable:
```suggestion
### Path to `FFMpeg` and `FFProbe` executables

The following are paths to the FFMpeg and FFProbe executables:
```

2024-08-21 14:56 UTC, anxumalo approved these changes
LGTM

2024-08-22 05:25 UTC, merged