[DOCS-6214] Identity service1.4
Alfresco/docs-alfresco pull request #189
Opened 2021-03-26 16:10 UTC by oliveralfresco2018

2021-03-31 14:24 UTC, anxumalo requested changes
Hi @jamalkm, are you able to confirm if the details in `/latest/support/index.md` are correct? Many thanks

2021-03-31 14:24 UTC, anxumalo commented on identity-service/latest/support/index.md
>  | Content Services 6.2.1 | Content Services supports the use of CMIS and authentication with the v1 REST APIs using the Identity Service. ADF and other modules are not currently supported for authent
Is ACS 6.x supported?

2021-04-06 09:19 UTC, stevenblair-al commented
approved.

2021-04-08 09:16 UTC, anxumalo commented on identity-service/latest/support/index.md
>  | Content Services 6.2.1 | Content Services supports the use of CMIS and authentication with the v1 REST APIs using the Identity Service. ADF and other modules are not currently supported for authent
Yes: confirmed in https://www.alfresco.com/services/subscription/technical-support/product-support-status

2021-04-08 09:20 UTC, anxumalo approved these changes

2021-04-08 10:39 UTC, merged