[DOCS-6134] Ags community
Alfresco/docs-alfresco pull request #254
Opened 2021-05-14 13:48 UTC by oliveralfresco2018

2021-05-17 14:08 UTC, anxumalo requested changes
Looks good but I have some questions:

- There are links to `governance-services/latest/` - should they all be `governance-services/community/`?
- `governance-services/community/install/docker.md` - line 18: this links to an old archived repo (ACS Community Deployment). The Docker Compose file for Community deployments has been renamed. See new file in https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml.
- `governance-services/community/develop/index.md` - line 15: has the Alfresco Community RM ReST API Explorer version changed with release? It still says `alfresco-rm-community-rest-api-explorer-3.0.a.war`.

2021-05-18 15:16 UTC, oliveralfresco2018 commented
I was required to add the SMC page which was missing from the migration.
The links that were 'latest' were pointing there because the page didnt exist in the comm version for whatever reason. It is an old page so I've just added it and updated all the links to be comm.
I think this is good to go know.

2021-05-20 13:00 UTC, oliveralfresco2018 commented on governance-services/community/develop/index.md
> +* [Alfresco Community RM ReST API Explorer](https://download.alfresco.com/cloudfront/release/community/RM/3.0.a/alfresco-rm-community-rest-api-explorer-3.5.a.war)
Updated to https://download.alfresco.com/cloudfront/release/community/RM/3.5.a/alfresco-governance-services-community-rest-api-explorer-3.5.a.war

2021-05-20 16:02 UTC, anxumalo approved these changes

2021-05-21 03:30 UTC, merged