[DOCS-6372] AGS Community
Alfresco/docs-alfresco pull request #397
Opened 2021-10-04 13:35 UTC by oliveralfresco2018

2021-10-04 16:01 UTC, anxumalo reviewed
For consistency, I'd also suggest deleting the following page & update the config (so it's similar to ACS Community) as it serves no real purpose: 
- `governance-services/community/support/index.md`

2021-10-05 10:38 UTC, oliveralfresco2018 commented on governance-services/community/develop/index.md
> +You can download the API Explorer `alfresco-governance-services-community-rest-api-explorer-11.140.war` from [Hyland Community](https://community.hyland.com/){:target="_blank"}.
Updated.

2021-10-05 10:55 UTC, oliveralfresco2018 commented on governance-services/community/install/zip.md
> +Download the Alfresco Governance Services distribution zip from [Hyland Community](https://community.hyland.com/){:target="_blank"}.
updated

2021-10-05 11:15 UTC, oliveralfresco2018 commented
Adjusted the comments plus adjusted the AGS Ent one also.

Cheers

2021-10-05 12:34 UTC, gravitonian requested changes
In http://localhost:4000/governance-services/community/install/docker/: you refer to 
 services:
     alfresco:
         #image: alfresco/alfresco-content-repository-community:7.0.0
         image: alfresco/alfresco-governance-repository-community:3.5.a

Is version 3.5.a correct???

2021-10-05 12:38 UTC, oliveralfresco2018 commented
Fixed that up thanks

2021-10-05 12:40 UTC, gravitonian approved these changes

2021-10-05 13:58 UTC, merged