DOCS-6488 initial pass at the process
Alfresco/docs-alfresco pull request #465
Opened 2021-11-24 12:25 UTC by oliveralfresco2018

2021-11-24 13:11 UTC, pmartinezga requested changes

2021-11-24 13:11 UTC, pmartinezga commented on process-automation/latest/model/forms.md
> +4. Add the File viewer widget to the form.
This step is not needed, The metadata viewer requires the attach widget to work but not the file viewer. THey usually appear together but it is not required

2021-11-24 13:11 UTC, pmartinezga commented on process-automation/latest/model/forms.md
> +8. From the **Linked attach file widget** drop down menu select the Attach file widget you want to link with the File viewer.
Not needed

2021-11-25 08:19 UTC, pmartinezga submitted a review, later dismissed

2021-11-25 10:43 UTC, anxumalo commented on process-automation/latest/model/forms.md
> +1. Create or edit an existing from, for more see [Create a form](#create-a-form).
typo?
```suggestion
1. Create or edit an existing form, for more see [Create a form](#create-a-form).
```

2021-11-25 12:51 UTC, anxumalo approved these changes

2021-11-25 12:58 UTC, merged