DOCS-6563 - mediation file update
Alfresco/docs-alfresco pull request #579
Opened 2022-03-17 14:27 UTC by oliveralfresco2018

2022-03-17 15:03 UTC, aonych approved these changes
LGTM

2022-03-23 13:28 UTC, gravitonian requested changes
Some formatting needed

2022-03-23 13:28 UTC, gravitonian commented on search-enterprise/latest/config/index.md
>  mediation:
Missing formatting of file content, so not displayed properly

2022-03-23 15:49 UTC, gravitonian approved these changes

2022-03-24 09:54 UTC, merged