[DOCS-6715] Update Teams integration installation instructions so we recommend app being installed by admin
Alfresco/docs-alfresco pull request #685
Opened 2022-06-13 08:34 UTC by gravitonian

Some images have also been updated. See also https://alfresco.atlassian.net/browse/ACS-2865

2022-06-14 12:04 UTC, oliveralfresco2018 approved these changes
LGTM, pending @montgolfiere review.

2022-06-14 12:04 UTC, oliveralfresco2018 commented on microsoft-teams/latest/install/index.md
> +available to the organisation's users.
```suggestion
available to the organization's users. 
```

2022-06-20 13:55 UTC, montgolfiere requested changes

2022-07-08 09:42 UTC, anxumalo requested changes
LGTM .. approved with minor suggestions

2022-07-08 09:42 UTC, anxumalo commented on microsoft-teams/latest/install/index.md
> +   ![MS Teams Admin Ceneter Manage Apps]({% link microsoft-teams/images/ms-teams-admin-center-manage-apps.png %})
```suggestion
   ![MS Teams Admin Center Manage Apps]({% link microsoft-teams/images/ms-teams-admin-center-manage-apps.png %})
```

2022-07-08 09:42 UTC, anxumalo commented on microsoft-teams/latest/install/index.md
> +5. If you search for something in the Alfresco app it will ask you to login, use your Alfresco credentials.
```suggestion
5. If you search for something in the Alfresco app it will ask you to login. Use your Alfresco credentials.
```

2022-07-08 12:31 UTC, merged