[DOCS-6823] Update New Folder, Move, Rename, Scan
Alfresco/docs-alfresco pull request #755
Opened 2022-08-01 14:09 UTC by Amy-Hyland

This is a first draft of the features in Mobile Workspace: New Folder, Move files. Rename files, and Scan files. Additional information requested has been added to the ticket.

2022-08-08 13:38 UTC, anxumalo commented on mobile-workspace/latest/using/index.md
> +3. Press the plus **+** button.
Is the plus (+) button the same as the floating action button?

2022-08-08 13:40 UTC, anxumalo commented on mobile-workspace/latest/using/index.md
> +3. Press the plus **+** button.
Is the plus (+) button the same as the "floating action" button?

```suggestion
3. Press the floating action button (**+**) button.
```

2022-08-08 13:45 UTC, anxumalo commented on mobile-workspace/latest/using/index.md
> +3. Select the Floating action button.
See comment for line 75 - suggested usage:
```suggestion
3. Select the floating action button (+).
```

2022-08-08 15:58 UTC, anxumalo requested changes
Please see my inline comments

2022-08-08 21:14 UTC, Amy-Hyland commented on mobile-workspace/latest/using/index.md
> +* If you do not wish to keep the scan, exit without saving. A dialog box will appear to confirm you want to **Discard** the scan. Select **Cancel** to return to save your scan.
Updated in my latest commit

2022-08-08 21:14 UTC, Amy-Hyland reviewed
I've incorporated all the changes in my latest commit.

2022-08-09 15:54 UTC, anxumalo approved these changes
LGTM 👍🏼

2022-08-09 16:29 UTC, merged