[DOCS-6673] Add Alfresco Extension Inspector 1.4
Alfresco/docs-alfresco pull request #758
Opened 2022-08-03 16:10 UTC by anxumalo

2022-08-03 21:20 UTC, Amy-Hyland approved these changes
LGTM

2022-08-04 01:59 UTC, jadeteen989 approved these changes

2022-08-04 08:29 UTC, aborroy requested changes
Missing parameter for the analyser option.

2022-08-04 08:29 UTC, aborroy commented on content-services/latest/develop/extension-inspector.md
>  where:
Adding following text could help to understand what `extension-filename` means:
| extension-filename | Mandatory. AMP or JAR file containing an Alfresco Extension

2022-08-04 10:04 UTC, aborroy approved these changes
LGTM

2022-08-04 10:09 UTC, merged