[DOCS-6927] Governance Services version bump 7.3
Alfresco/docs-alfresco pull request #829
Opened 2022-10-21 12:37 UTC by oliveralfresco2018

2022-11-14 13:51 UTC, mjstanford approved these changes

2022-11-15 12:59 UTC, anxumalo requested changes
Looks good - minor corrections to consider:

In `governance-services/latest/install/docker.md`:
- add the usual "target=_blank" for external links (3 instances)
- update the dates in step 7 by running the `docker-compose.yml` script from `acs-deployment/docker-compose/` 

In `governance-services/latest/uninstall.md`, update the **Install Date** to match the release date/year (2 instances).

2022-11-15 12:59 UTC, anxumalo commented on governance-services/latest/install/zip.md
> +1. Browse to the [Alfresco Nexus repository](https://nexus.alfresco.com/nexus/#nexus-search;gav~org.alfresco~alfresco-governance*~7.3.0~~){:target="_blank"} and download `alfresco-governance-services
This shows me the Community ZIP in Nexus when I'm not logged in - is this the expected behaviour?

2022-11-15 13:09 UTC, anxumalo commented on governance-services/latest/install/zip.md
> +1. Browse to the [Alfresco Nexus repository](https://nexus.alfresco.com/nexus/#nexus-search;gav~org.alfresco~alfresco-governance*~7.3.0~~){:target="_blank"} and download `alfresco-governance-services
Enterprise customers should access Hyland Community - Community users should go to Nexus (also added comment in PR #860 ). If you prefer, you can add a direct link to the Hyland Community release page for AGS Enterprise.

```suggestion
1. Browse to [Hyland Community](https://community.hyland.com/){:target="_blank"} and download `alfresco-governance-services-enterprise-distribution-7.3.0.zip`.
```

2022-11-16 13:46 UTC, anxumalo approved these changes

2022-11-16 14:52 UTC, merged