[DOCS-7013] Fix site config for latest DTE 2.3 docs
Alfresco/docs-alfresco pull request #864
Opened 2022-11-11 17:36 UTC by anxumalo

If you go to any [Alfresco Document Transformation Engine v2.2 docs page](https://docs.alfresco.com/transformation-engine/2.2/) and then try to switch to the `latest` docs by selecting **2.3 latest** from the dropdown, it just switches back to showing the earlier `2.2` release docs. This is because the **latest** version is set twice, for `2.2 `and `2.3`. This PR removes the latest setting from the 2.2 version.

2022-11-11 17:44 UTC, isandhu commented
Looks good to me.

2022-11-11 18:01 UTC, isandhu approved these changes
Looks good to me.

2022-11-11 18:04 UTC, Amy-Hyland requested changes
When I tried the fix, my local http://localhost:4000/transformation-engine/2.2/ did not change as expected to the latest 2.3 version when using the version drop down menu.

2022-11-15 08:28 UTC, anxumalo commented
> When I tried the fix, my local http://localhost:4000/transformation-engine/2.2/ did not change as expected to the latest 2.3 version when using the version drop down menu. It turns out, my git pull isn't pulling the changes down... I'm not sure why.

Thanks for checking @Amy-Hyland - please try to fix your local environment first and then try the docs build again.

2022-11-15 09:10 UTC, oliveralfresco2018 commented
Built and tested. Seems to be ok now.

2022-11-15 09:15 UTC, oliveralfresco2018 approved these changes
LGTM

2022-11-15 10:39 UTC, merged