[DOCS-6501] Add CMIS support
Alfresco/docs-alfresco pull request #879
Opened 2022-11-18 12:24 UTC by oliveralfresco2018

2022-11-18 12:35 UTC, mjstanford requested changes

2022-11-24 12:42 UTC, oliveralfresco2018 commented on search-enterprise/latest/using/languages.md
>  ## Lucene Query Language
Added after meeting discussion

2022-11-24 13:23 UTC, mjstanford approved these changes

2022-11-24 15:27 UTC, anxumalo approved these changes
LGTM 👍🏼 

I changed the language indicators to lowercase, and also tried adding a tooltip for AFTS but that didn't work so well!

2022-11-24 15:35 UTC, merged