[DOCS-7123] Alfresco Content Accelerator 3.5.1
Alfresco/docs-alfresco pull request #958
Opened 2023-03-24 20:45 UTC by Amy-Hyland

2023-03-30 21:14 UTC, Amy-Hyland commented
I believe the post ACA 3.5 changes have all been applied to the current branch.

2023-03-31 15:30 UTC, katiebrill approved these changes
Looks great to me. Thanks so much team!

2023-04-14 14:35 UTC, anxumalo requested changes
Looks good - see inline comments for suggested improvements

2023-04-14 20:51 UTC, Amy-Hyland commented on content-accelerator/latest/configure/actions.md
Yes, this page does need a lot of edits.

2023-04-14 21:54 UTC, Amy-Hyland commented on content-accelerator/latest/configure/other-aca-admin-configs.md
> +> **Note:** DataDictionary picklists are reserved for future use and are not currently supported.
I changed this and I few other items. I restrained from editing more.

2023-04-17 08:54 UTC, anxumalo approved these changes
LGTM 👍🏼

2023-04-18 20:08 UTC, merged