[DOCS-6502] Unsupported multilingual removed
Alfresco/docs-alfresco pull request #972
Opened 2023-04-12 09:27 UTC by oliveralfresco2018

2023-05-04 13:38 UTC, mjstanford requested changes

2023-05-09 12:31 UTC, oliveralfresco2018 commented on _data/toc/search-enterprise.yaml
> +        - title: 'Multiple language support'
Corrected

2023-05-09 12:31 UTC, oliveralfresco2018 commented on search-enterprise/latest/config/language.md
> +title: Multiple language support
Corrected

2023-05-09 12:45 UTC, mjstanford approved these changes

2023-05-10 12:04 UTC, anxumalo requested changes
Added a few suggestions

2023-05-10 13:52 UTC, merged