[DOCS-7213] ACS 7.4 Admin - Hazelcast security
Alfresco/docs-alfresco pull request #989
Opened 2023-04-27 21:32 UTC by Amy-Hyland

Add documentation to the cluster section describing important actions required to harden the cluster and prevent exposing sensitive data.

2023-04-28 08:53 UTC, damianujma approved these changes

2023-05-04 14:27 UTC, anxumalo requested changes
Looks good - just 2 minor typos to fix

2023-05-04 14:27 UTC, anxumalo commented on content-services/latest/admin/cluster.md
> +Depending on your organization security policies and guidelines, a Hazelcast Enterprise license might be required to implement further hardening on the cluster. Alfresco does not provide this license
```suggestion
Depending on your organization security policies and guidelines, a Hazelcast Enterprise license might be required to implement further hardening on the cluster. Alfresco does not provide this license so please refer to the [Hazelcast Security Suite](https://hazelcast.com/product-features/security-suite/){:target="_blank"} for details.

```

2023-05-04 15:37 UTC, anxumalo approved these changes

2023-05-10 20:16 UTC, merged