[DOCS-7218] Add WCAG information
Alfresco/docs-alfresco pull request #990
Opened 2023-04-28 12:40 UTC by oliveralfresco2018

2023-05-05 16:36 UTC, anxumalo requested changes
Sending early feedback suggestions

2023-05-05 16:36 UTC, anxumalo commented on digital-workspace/latest/index.md
> +## WCAG 2.1
```suggestion
## Web Content Accessibility Guidelines (WCAG) 2.1
```

2023-05-05 16:36 UTC, anxumalo commented on digital-workspace/latest/index.md
> +The Digital Workspace has been independently tested for its accessability using the WCAG 2.1 AA, Section 508, and EN 301 standards. It complies with these regulations that ensure an online computer b
```suggestion
The Digital Workspace has been independently tested for its accessibility using the WCAG 2.1 AA, Section 508, and EN 301 standards. It complies with these regulations that ensure an online computer-based system is completely accessible by all of the general public, including those with disabilities. See the following websites for more details:

* [Understanding WCAG 2.1](https://www.gov.uk/service-manual/helping-people-to-use-your-service/understanding-wcag){:target="_blank"}
* [WCAG 2.1 Guidelines](https://www.w3.org/TR/WCAG21){:target="_blank"}
* [Government-wide Section 508 Assessment](https://www.section508.gov/){:target="_blank"}
* [EN 301 549 - Accessibility requirements for ICT products and services](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf){:target="_blank"}.

```

2023-05-09 12:36 UTC, oliveralfresco2018 commented on digital-workspace/latest/index.md
> +The Digital Workspace has been independently tested for its accessability using the WCAG 2.1 AA, Section 508, and EN 301 standards. It complies with these regulations that ensure an online computer b
cheers

2023-05-11 10:03 UTC, anxumalo approved these changes
LGTM

2023-05-11 10:27 UTC, merged